---
- when: k3s.download.state == "absent"
  block:
    - name: Remove k3s binaries
      loop:
        - path: /usr/local/bin/k3s
      file:
        path: '{{ item.path }}'
        state: absent

- when: k3s.download.state == "present"
  block:
    - name: Download k3s binaries
      loop:
        - bin: 'https://github.com/k3s-io/k3s/releases/download/{{ k3s.download.version }}/{{ _k3s_files[ansible_facts.architecture].bin }}'
          sha256: 'https://github.com/k3s-io/k3s/releases/download/{{ k3s.download.version }}/{{ _k3s_files[ansible_facts.architecture].sha256 }}'
          path: '/usr/local/bin/k3s'
      get_url:
        url: '{{ item.bin }}'
        checksum: 'sha256:{{ item.sha256 }}'
        dest: '{{ item.path }}'
        owner: root
        group: root
        mode: 0755
