---
- name: Gather facts
  hosts: k3s
  tags:
    - always

- name: Prepare Proxmox cluster
  hosts: proxmox
  environment: '{{ proxy.env if proxy.configure else {} }}'
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - role: proxmox_lxc
      when: proxmox_lxc.configure
  tags:
    - never
    - hypervisor

- name: Prepare k3s nodes
  hosts: k3s
  environment: '{{ proxy.env if proxy.configure else {} }}'
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - role: lxc
      when: proxmox_lxc.configure
    - role: prereq
    - role: download
      when: k3s.download.state | default("disabled") != "disabled"
    - role: install
      when: k3s.install.state | default("disabled") != "disabled"
    - role: k3s_custom_registries
      when: custom_registries.configure
  tags:
    - always
    - nodes

- name: Setup k3s servers
  hosts: k3s_server
  environment: '{{ proxy.env if proxy.configure else {} }}'
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - role: k3s_server
  tags:
    - never
    - k3s
    - k3s_server

- name: Setup k3s agents
  hosts: k3s_agent
  environment: '{{ proxy.env if proxy.configure else {} }}'
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - role: k3s_agent
  tags:
    - never
    - k3s
    - k3s_agent

- name: Configure k3s cluster
  hosts: k3s_server
  environment: '{{ proxy.env if proxy.configure else {} }}'
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - role: k3s_server_post
  tags:
    - never
    - k3s
    - k3s_manifests
