---
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  when: ansible_facts.os_family == "RedHat"

- name: Load modules
  community.general.modprobe:
    name: '{{ item }}'
    state: present
    persistent: present
  loop:
    - br_netfilter
    - overlay

- name: Configure IP forwarding
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
  loop:
    - { name: "net.ipv4.ip_forward", value: "1" }
    - { name: "net.ipv6.conf.all.forwarding", value: "1" }

- name: Configure IPv6 RA
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
  loop:
    - { name: "net.ipv6.conf.all.accept_ra", value: "2" }

- name: Configure bridge netfilter
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
  loop:
    - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { name: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
