---
- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
  when: ansible_facts.os_family == "RedHat"

- name: Load modules
  community.general.modprobe:
    name: '{{ item }}'
    state: present
    persistent: present
  loop:
    - br_netfilter
    - overlay

- name: Configure kernel
  ansible.posix.sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
    sysctl_file: '/etc/sysctl.d/80-ansible.conf'
    sysctl_set: true
    reload: false
  loop:
    - { name: "net.ipv4.ip_forward", value: "1" }
    - { name: "net.ipv6.conf.all.forwarding", value: "1" }
    - { name: "net.ipv6.conf.all.accept_ra", value: "2" }
    - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }
    - { name: "net.bridge.bridge-nf-call-ip6tables", value: "1" }

- name: NFS
  block:
    - name: Install NFS packages
      community.general.pacman:
        name:
          - nfs-utils
        state: 'installed'

    - name: Enable NFS client
      systemd:
        name: nfs-client.target
        state: started
        enabled: true
