---
- name: Insert registries into /etc/rancher/k3s/registries.yaml
  blockinfile:
    path: /etc/rancher/k3s/registries.yaml
    block: '{{ custom_registries.manifest }}'
    state: '{{ custom_registries.state | default("present") }}'
    create: true
    mode: '0600'
