---
- name: Deploy additional k3s manifests
  when: k3s.extras and inventory_hostname == groups["k3s_server"][0]
  vars:
    _k3s_manifests_dir: /tmp/k3s/manifests
  block:
    - name: Create manifests directory
      file:
        path: '{{ _k3s_manifests_dir }}'
        state: directory

    - name: Deploy MetalLB manifests
      include_tasks: deploy_metallb.yml
  always:
    - name: Remove manifests directory
      file:
        path: '{{ _k3s_manifests_dir }}'
        state: absent
