---
- name: Install k3s configuration
  vars:
    _k3s_units_env:
      "k3s-init.service":
        "K3S_EXEC": '{{ _k3s_args_server_init | split() | join(" ") }}'
      "k3s.service":
        "K3S_EXEC": '{{ _k3s_args_server | split() | join(" ") }}'
    _k3s_configs_dir: /etc/rancher/k3s/config.yaml.d
    _k3s_configs: '{{ _k3s_configs_all }}'
  block:
    - name: Create configuration directory
      file:
        path: '{{ _k3s_configs_dir }}'
        state: directory

    - name: Install configuration files
      copy:
        content: '{{ item.value }}'
        dest: "{{ _k3s_configs_dir }}/{{ item.key }}"
        mode: "0600"
      when: item.value is match("\S")
      loop: '{{ _k3s_configs | dict2items }}'
      loop_control:
        label: '{{ item.key }}'
      notify: k3s_restart

    - debug:
        msg: '{{ _k3s_configs }}'

    - name: Install environment files
      copy:
        content: |-
          # Mandatory configuration
          {% for k, v in _k3s_units_env[item].items() %}
          {{ k }}={{ v }}
          {% endfor %}

          {% if proxy.configure %}
          # Proxy configuration
          {% for k, v in proxy.env.items() %}
          {{ k }}={{ v }}
          {% endfor %}
          {% endif %}
        dest: "{{ _systemd_dir }}/{{ item }}.env"
        mode: '0600'
      loop: '{{ _k3s_units_env.keys() }}'
      notify: k3s_reinit

    - debug:
        msg: '{{ _k3s_units_env }}'

- name: Install k3s manifests
  when: k3s.extras and inventory_hostname == groups["k3s_server"][0]
  vars:
    _k3s_manifests_dir: /var/lib/rancher/k3s/server/manifests
  block:
    - name: Create manifests directory
      file:
        path: '{{ _k3s_manifests_dir }}'
        state: directory

    - name: Install kube-vip manifests
      include_tasks: install_kube_vip.yml

    - name: Install MetalLB manifests
      include_tasks: install_metallb.yml

- name: Check tokens
  stat:
    path: "{{ _k3s_state_dir }}/server/{{ item }}"
  loop:
    - node-token
    - agent-token
  register: this
  changed_when: not this.stat.exists
  notify: k3s_reinit

- name: Commit reinit flag
  meta: flush_handlers

- name: Initialize k3s
  when: _k3s_reinit or _k3s_force_reinit
  block:
    - name: Stop and reset k3s units
      systemd_service:
        name: '{{ item }}'
        state: stopped
        reset_failed: true
      failed_when: false
      loop:
        - k3s-init.service
        - k3s.service

    - name: Get journal cursor
      command:
        argv: [
          "journalctl",
          "-n1",
          "-ojson",
          "--output-fields=__CURSOR",
        ]
      changed_when: false
      register: _k3s_init_cursor

    - name: Run k3s-init.service
      command:
        argv: [
          "systemd-run",
          "--unit=k3s-init.service",
          # FIXME: non-first masters may fail briefly until 1st master is up, so run them with Type=exec
          '{{ "-pType=notify" if inventory_hostname == groups["k3s_server"][0] else "-pType=exec" }}',
          "-pEnvironmentFile={{ _systemd_dir }}/k3s-init.service.env",
          "-pKillMode=process",
          "-pDelegate=yes",
          "-pRestartSec=2",
          "-pRestart=on-failure",
          "--",
          "k3s",
          "server",
          "$K3S_EXEC",
        ]
      register: this
    - debug:
        msg: '{{ this.stdout + this.stderr }}'

    - name: Wait for k3s initialization
      when: not ansible_check_mode
      include_tasks: k3s_wait_up.yml

    - name: 'HACK: wait for 60s'
      when: not ansible_check_mode
      wait_for:
        timeout: 60

  always:
    - name: Fetch final node status
      command:
        argv: [
          "k3s",
          "kubectl",
          "get",
          "nodes",
          "-l=node-role.kubernetes.io/master=true",
          "-o=wide",
        ]
      changed_when: false
      failed_when: false
      register: nodes

    - name: Terminate k3s-init.service
      systemd:
        name: k3s-init.service
        state: stopped
        reset_failed: true

    - name: Fetch k3s-init.service logs
      command:
        argv: [
          "journalctl",
          "--all",
          "--unit=k3s-init.service",
          '--after-cursor={{ (_k3s_init_cursor.stdout | from_json)["__CURSOR"] }}',
        ]
      changed_when: false
      register: logs

    - name: Create local directories
      delegate_to: localhost
      become: false
      file:
        path: '{{ item }}'
        state: directory
      loop:
        - '{{ _k3s_log_destination }}'

    - name: Store node status
      delegate_to: localhost
      become: false
      copy:
        content: '{{ nodes.stdout }}'
        dest: "{{ _k3s_log_destination }}/k3s-init-nodes@{{ inventory_hostname }}.log"

    - name: Store k3s-init.service logs
      delegate_to: localhost
      become: false
      copy:
        content: '{{ logs.stdout }}'
        dest: "{{ _k3s_log_destination }}/k3s-init-log@{{ inventory_hostname }}.log"

- name: Enable and run k3s.service
  systemd:
    name: k3s.service
    enabled: true
    state: '{{ "restarted" if _k3s_restart or _k3s_force_restart else "started" }}'

- name: Wait for k3s
  when: not ansible_check_mode
  include_tasks: k3s_wait_up.yml

- name: Read k3s configuration
  when: not ansible_check_mode
  # and inventory_hostname == groups["k3s_server"][0]
  block:
    # ffs, ansible, give us blocks in loops
    - name: Read tokens
      slurp:
        path: "{{ _k3s_state_dir }}/server/{{ item.src }}"
      loop:
        - { src: node-token, fact: _k3s_node_token }
        - { src: agent-token, fact: _k3s_agent_token }
      register: tokens

    - name: Store tokens
      set_fact:
        '{{ item.item.fact }}': '{{ item.content | b64decode | trim }}'
        cacheable: true
      loop: '{{ tokens.results }}'
      loop_control:
        label: '{{ item.item }}'

    - debug:
        msg: '{{ _k3s_node_token }}'
    - debug:
        msg: '{{ _k3s_agent_token }}'
    - debug:
        msg: '{{ _k3s_init_token }}'

    - name: Copy kubeconfig
      copy:
        remote_src: true
        src: "{{ _k3s_conf_dir }}/k3s.yaml"
        dest: "{{ _k3s_conf_dir }}/k3s.yaml.tmp"
      changed_when: false

    - name: Adjust kubeconfig context and cluster name to {{ _k3s_cfg_context_name }}
      replace:
        path: "{{ _k3s_conf_dir }}/k3s.yaml.tmp"
        regexp: "\\b(current-context|cluster|user|name): default$"
        replace: "\\1: {{ _k3s_cfg_context_name }}"
      changed_when: false

    - name: Adjust kubeconfig endpoint URL to local node name
      vars:
        endpoint_url: "https://{{ _k3s_ext_node_name | ansible.utils.ipwrap }}:6443"
      replace:
        path: "{{ _k3s_conf_dir }}/k3s.yaml.tmp"
        regexp: "\\b(server): [^\\n]+$"
        replace: "\\1: {{ endpoint_url }}"
      changed_when: false

    - name: Create ~/.kube
      file:
        path: "{{ ansible_facts.user_dir }}/.kube"
        state: directory

    - name: Copy kubeconfig to ~/.kube
      copy:
        remote_src: true
        src: "{{ _k3s_conf_dir }}/k3s.yaml.tmp"
        dest: "{{ ansible_facts.user_dir }}/.kube/config"

- name: Download k3s configuration
  when: not ansible_check_mode and inventory_hostname == groups["k3s_server"][0]
  block:
    - name: Copy kubeconfig (user)
      copy:
        remote_src: true
        src: "{{ _k3s_conf_dir }}/k3s.yaml.tmp"
        dest: "{{ _k3s_conf_dir }}/k3s.yaml.tmp.user"
      changed_when: false

    - name: Adjust kubeconfig (user) endpoint URL to {{ endpoint_url }}
      vars:
        endpoint_url: "https://{{ _k3s_apiserver_name | ansible.utils.ipwrap }}:6443"
      replace:
        path: "{{ _k3s_conf_dir }}/k3s.yaml.tmp.user"
        regexp: "\\b(server): [^\\n]+$"
        replace: "\\1: {{ endpoint_url }}"
      changed_when: false

    - name: Create local directories
      delegate_to: localhost
      become: false
      file:
        path: '{{ item }}'
        state: directory
      loop:
        - '{{ _k3s_conf_destination }}'

    - name: Fetch k3s configuration
      vars:
        src: '{{ item.src }}'
        dest: '{{ _k3s_conf_destination }}/{{ item.dest | default(item.src | basename) }}'
      fetch:
        src: "{{ src }}"
        dest: "{{ dest }}"
        flat: true
      loop:
        - { src: "{{ _k3s_state_dir }}/server/node-token" }
        - { src: "{{ _k3s_state_dir }}/server/agent-token" }
        - { src: "{{ _k3s_conf_dir }}/k3s.yaml.tmp.user", dest: kubeconfig }

- name: Find k3s tool
  command:
    argv: [
      "which",
      "k3s",
    ]
  changed_when: false
  register: this

- name: Create {{ item }} symlink
  file:
    src: '{{ this.stdout }}'
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - kubectl
    - crictl
    - ctr
